branch: develop
check:
  - CKV_DOCKER_1
compact: true
directory:
  - test-dir
docker-image: sample-image
dockerfile-path: Dockerfile
download-external-modules: true
evaluate-variables: true
external-checks-dir:
  - sample-dir
external-modules-download-path: .external_modules
framework: all
no-guide: true
output: cli
quiet: true
repo-id: bridgecrew/sample-repo
skip-check:
  - CKV_DOCKER_3
  - CKV_DOCKER_2
skip-fixes: true
skip-framework: dockerfile
skip-suppressions: true
soft-fail: true
